import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/splashscreen">SplashScreen</Link>
        </li>
        <li>
          <Link to="/signupvendoraccount">SIGNUPVendorAccount</Link>
        </li>
        <li>
          <Link to="/profilecustomer">ProfileCustomer</Link>
        </li>
        <li>
          <Link to="/productlistpage">ProductlistPage</Link>
        </li>
        <li>
          <Link to="/cart">Cart</Link>
        </li>
        <li>
          <Link to="/checkoutdelivery">Checkoutdelivery</Link>
        </li>
        <li>
          <Link to="/payment">Payment</Link>
        </li>
        <li>
          <Link to="/successful">Successful</Link>
        </li>
        <li>
          <Link to="/confirm">Confirm</Link>
        </li>
        <li>
          <Link to="/createaccount">CreateAccount</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
